sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nikolacolakovic/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true nikolacolakovic/react-test npm run test -- --caverage

after_success:
  - docker build -t nikolacolakovic/multi-client ./client
  - docker build -t nikolacolakovic/multi-nginx ./nginx
  - docker build -t nikolacolakovic/multi-server ./server
  - docker build -t nikolacolakovic/multi-worker ./worker


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-923445559289"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
