version: '1'
services:
  client:
    image: "rallycoding/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "rellycoding/multi-server"
    mem_limit: 128m
    hostname: api   
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "rellycoding/multi-worker"
    mem_limit: 128m
    hostname: worker       
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT 
  nginx:
    image: "rellycoding/multi-multi"
    mem_limit: 128m
    hostname: nginx     
    ports:
      - "80:80"

